all_data_album = {'href': 'https://api.spotify.com/v1/artists/0oL7mgftYGFe5wWq0b9G4g/albums?include_groups=album&offset=0&limit=20',
 'items': [{'album_group': 'album',
   'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oL7mgftYGFe5wWq0b9G4g'},
     'href': 'https://api.spotify.com/v1/artists/0oL7mgftYGFe5wWq0b9G4g',
     'id': '0oL7mgftYGFe5wWq0b9G4g',
     'name': 'lllit',
     'type': 'artist',
     'uri': 'spotify:artist:0oL7mgftYGFe5wWq0b9G4g'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/30Ou1iVNvjR9GoxcblxN0d'},
   'href': 'https://api.spotify.com/v1/albums/30Ou1iVNvjR9GoxcblxN0d',
   'id': '30Ou1iVNvjR9GoxcblxN0d',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b2736968c6857aa2815faae9e5b2',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e026968c6857aa2815faae9e5b2',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d000048516968c6857aa2815faae9e5b2',
     'width': 64}],
   'name': 'Broken Abst',
   'release_date': '2024-05-17',
   'release_date_precision': 'day',
   'total_tracks': 6,
   'type': 'album',
   'uri': 'spotify:album:30Ou1iVNvjR9GoxcblxN0d'},
  {'album_group': 'album',
   'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oL7mgftYGFe5wWq0b9G4g'},
     'href': 'https://api.spotify.com/v1/artists/0oL7mgftYGFe5wWq0b9G4g',
     'id': '0oL7mgftYGFe5wWq0b9G4g',
     'name': 'lllit',
     'type': 'artist',
     'uri': 'spotify:artist:0oL7mgftYGFe5wWq0b9G4g'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/7E99Uo5NgiPGOoY5LbVBJE'},
     'href': 'https://api.spotify.com/v1/artists/7E99Uo5NgiPGOoY5LbVBJE',
     'id': '7E99Uo5NgiPGOoY5LbVBJE',
     'name': 'Alejada',
     'type': 'artist',
     'uri': 'spotify:artist:7E99Uo5NgiPGOoY5LbVBJE'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/7C7UpEE6TO11VT2HZ8hS7L'},
     'href': 'https://api.spotify.com/v1/artists/7C7UpEE6TO11VT2HZ8hS7L',
     'id': '7C7UpEE6TO11VT2HZ8hS7L',
     'name': 'Ernis',
     'type': 'artist',
     'uri': 'spotify:artist:7C7UpEE6TO11VT2HZ8hS7L'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/28BcVxBeXqYgqXAHDsi4uT'},
   'href': 'https://api.spotify.com/v1/albums/28BcVxBeXqYgqXAHDsi4uT',
   'id': '28BcVxBeXqYgqXAHDsi4uT',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273e20a2846bd5a05bb999b6b4b',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02e20a2846bd5a05bb999b6b4b',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851e20a2846bd5a05bb999b6b4b',
     'width': 64}],
   'name': 'Ecosfera',
   'release_date': '2023-10-06',
   'release_date_precision': 'day',
   'total_tracks': 5,
   'type': 'album',
   'uri': 'spotify:album:28BcVxBeXqYgqXAHDsi4uT'},
  {'album_group': 'album',
   'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oL7mgftYGFe5wWq0b9G4g'},
     'href': 'https://api.spotify.com/v1/artists/0oL7mgftYGFe5wWq0b9G4g',
     'id': '0oL7mgftYGFe5wWq0b9G4g',
     'name': 'lllit',
     'type': 'artist',
     'uri': 'spotify:artist:0oL7mgftYGFe5wWq0b9G4g'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/6DmTZGEixoYFqjUMR9IpNk'},
     'href': 'https://api.spotify.com/v1/artists/6DmTZGEixoYFqjUMR9IpNk',
     'id': '6DmTZGEixoYFqjUMR9IpNk',
     'name': 'Bleupulp',
     'type': 'artist',
     'uri': 'spotify:artist:6DmTZGEixoYFqjUMR9IpNk'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/2cNrFUn1asPCLcjut7LxcX'},
     'href': 'https://api.spotify.com/v1/artists/2cNrFUn1asPCLcjut7LxcX',
     'id': '2cNrFUn1asPCLcjut7LxcX',
     'name': 'Retouched',
     'type': 'artist',
     'uri': 'spotify:artist:2cNrFUn1asPCLcjut7LxcX'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/4pjhkhfoGXZ6yDKSWMRBFx'},
   'href': 'https://api.spotify.com/v1/albums/4pjhkhfoGXZ6yDKSWMRBFx',
   'id': '4pjhkhfoGXZ6yDKSWMRBFx',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273e8c351cf71af27267492505d',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02e8c351cf71af27267492505d',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851e8c351cf71af27267492505d',
     'width': 64}],
   'name': 'Dirt Dub',
   'release_date': '2023-09-14',
   'release_date_precision': 'day',
   'total_tracks': 8,
   'type': 'album',
   'uri': 'spotify:album:4pjhkhfoGXZ6yDKSWMRBFx'},
  {'album_group': 'album',
   'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oL7mgftYGFe5wWq0b9G4g'},
     'href': 'https://api.spotify.com/v1/artists/0oL7mgftYGFe5wWq0b9G4g',
     'id': '0oL7mgftYGFe5wWq0b9G4g',
     'name': 'lllit',
     'type': 'artist',
     'uri': 'spotify:artist:0oL7mgftYGFe5wWq0b9G4g'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/4VXnt0WOFoMgp7fa224FL6'},
   'href': 'https://api.spotify.com/v1/albums/4VXnt0WOFoMgp7fa224FL6',
   'id': '4VXnt0WOFoMgp7fa224FL6',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273f45da560fa522e0174f6259c',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02f45da560fa522e0174f6259c',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851f45da560fa522e0174f6259c',
     'width': 64}],
   'name': 'Hiperbórea',
   'release_date': '2023-01-03',
   'release_date_precision': 'day',
   'total_tracks': 7,
   'type': 'album',
   'uri': 'spotify:album:4VXnt0WOFoMgp7fa224FL6'},
  {'album_group': 'album',
   'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oL7mgftYGFe5wWq0b9G4g'},
     'href': 'https://api.spotify.com/v1/artists/0oL7mgftYGFe5wWq0b9G4g',
     'id': '0oL7mgftYGFe5wWq0b9G4g',
     'name': 'lllit',
     'type': 'artist',
     'uri': 'spotify:artist:0oL7mgftYGFe5wWq0b9G4g'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/4lESNqKe26X4jE0JspKpMn'},
   'href': 'https://api.spotify.com/v1/albums/4lESNqKe26X4jE0JspKpMn',
   'id': '4lESNqKe26X4jE0JspKpMn',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b27370a3f32d0c4609d500f91ed2',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e0270a3f32d0c4609d500f91ed2',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d0000485170a3f32d0c4609d500f91ed2',
     'width': 64}],
   'name': 'Magickspaces',
   'release_date': '2022-12-06',
   'release_date_precision': 'day',
   'total_tracks': 6,
   'type': 'album',
   'uri': 'spotify:album:4lESNqKe26X4jE0JspKpMn'},
  {'album_group': 'album',
   'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oL7mgftYGFe5wWq0b9G4g'},
     'href': 'https://api.spotify.com/v1/artists/0oL7mgftYGFe5wWq0b9G4g',
     'id': '0oL7mgftYGFe5wWq0b9G4g',
     'name': 'lllit',
     'type': 'artist',
     'uri': 'spotify:artist:0oL7mgftYGFe5wWq0b9G4g'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/07mHcnkbVAupmBJum63rrB'},
   'href': 'https://api.spotify.com/v1/albums/07mHcnkbVAupmBJum63rrB',
   'id': '07mHcnkbVAupmBJum63rrB',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b2734f4fe2e9bd61a1b8d6b96bc6',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e024f4fe2e9bd61a1b8d6b96bc6',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d000048514f4fe2e9bd61a1b8d6b96bc6',
     'width': 64}],
   'name': 'Flames Underwater',
   'release_date': '2022-12-05',
   'release_date_precision': 'day',
   'total_tracks': 5,
   'type': 'album',
   'uri': 'spotify:album:07mHcnkbVAupmBJum63rrB'},
  {'album_group': 'album',
   'album_type': 'album',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oL7mgftYGFe5wWq0b9G4g'},
     'href': 'https://api.spotify.com/v1/artists/0oL7mgftYGFe5wWq0b9G4g',
     'id': '0oL7mgftYGFe5wWq0b9G4g',
     'name': 'lllit',
     'type': 'artist',
     'uri': 'spotify:artist:0oL7mgftYGFe5wWq0b9G4g'}],
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/7ApEL8eOqNELunZiLO7u9n'},
   'href': 'https://api.spotify.com/v1/albums/7ApEL8eOqNELunZiLO7u9n',
   'id': '7ApEL8eOqNELunZiLO7u9n',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b2730a170bb3efb83d6ef03968dd',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e020a170bb3efb83d6ef03968dd',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d000048510a170bb3efb83d6ef03968dd',
     'width': 64}],
   'name': 'Eudaimonia',
   'release_date': '2022-05-22',
   'release_date_precision': 'day',
   'total_tracks': 9,
   'type': 'album',
   'uri': 'spotify:album:7ApEL8eOqNELunZiLO7u9n'}],
 'limit': 20,
 'next': None,
 'offset': 0,
 'previous': None,
 'total': 7}